services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
       - /usr/src/app/node_modules 
       - ./db.sqlite:/usr/src/app/db.sqlite
    environment:
      NODE_ENV: production

volumes:
  sqlite-data: